-dontwarn com.oasisfeng.condom.CondomContext$CondomContentResolver
-dontwarn com.oasisfeng.condom.ContentResolverWrapper
-dontwarn com.oasisfeng.condom.PackageManagerWrapper
-dontwarn com.oasisfeng.condom.PseudoContextWrapper
-dontwarn com.oasisfeng.condom.kit.NullDeviceIdKit$CondomTelephonyManager
-keep class com.oasisfeng.condom.**